# Generated by Django 5.2.18 on 2026-10-08 23:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='título')),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(5000)], verbose_name='descrição')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta'), (4, 'Crítica')], default=2, verbose_name='prioridade')),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('IN_PROGRESS', 'Em atendimento'), ('WAITING_REQUESTER', 'Aguardando solicitante'), ('RESOLVED', 'Resolvido'), ('CLOSED', 'Fechado'), ('CANCELLED', 'Cancelado')], default='OPEN', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolvido em')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='fechado em')),
                ('assignee', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'role': 'TECHNICIAN'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.category', verbose_name='categoria')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_tickets', to=settings.AUTH_USER_MODEL, verbose_name='solicitante')),
            ],
            options={
                'verbose_name': 'chamado',
                'verbose_name_plural': 'chamados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='texto')),
                ('is_internal', models.BooleanField(default=False, verbose_name='nota interna')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket', verbose_name='chamado')),
            ],
            options={
                'verbose_name': 'comentário',
                'verbose_name_plural': 'comentários',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Criado'), ('UPDATED', 'Atualizado'), ('STATUS_CHANGED', 'Status alterado'), ('ASSIGNED', 'Atribuído')], max_length=20, verbose_name='ação')),
                ('field', models.CharField(blank=True, max_length=50, verbose_name='campo')),
                ('old_value', models.TextField(blank=True, verbose_name='valor anterior')),
                ('new_value', models.TextField(blank=True, verbose_name='valor novo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_changes', to=settings.AUTH_USER_MODEL, verbose_name='autor da alteração')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tickets.ticket', verbose_name='chamado')),
            ],
            options={
                'verbose_name': 'histórico do chamado',
                'verbose_name_plural': 'históricos dos chamados',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='tickets_tic_status_0e5646_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority'], name='tickets_tic_priorit_0bec9b_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='tickets_tic_created_5dd600_idx'),
        ),
    ]
